<h1>Manage posts</h1>

<p>
	<a class="btn btn-primary" href="admin_edit.html">Add a new post</a>
</p>

<table class="table table-striped">
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Category</th>
			<th>Publication date</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->entries as $post): ?>
			<tr>
				<td><?= $post->getId() ?></td>
				<td><?= $post->getName() ?></td>
				<td><?= $post->getCategoryId() ?></td>
				<td><?= $post->getCreated() ?></td>
				<td>
					<a class="btn btn-primary" 
						href="<?= $this->url(array('id'=>$post->id ), 'edit_post') ?>">Edit</a>
					<a class="btn btn-danger"  
						href="<?= $this->url(array('id'=>$post->id ), 'delete_post') ?>">Delete</a>
				</td>
			</tr>
		<?php endforeach ?>
	</tbody>
</table>