<div class="row">

	<div class="col-md-8">

		<div class="page-header">
			<h1><?= $this->title ?></h1>
			<p>Welcome to my blog</p>
		</div>

		<?php foreach ($this->entries as $post): ?>
			<article>
				<h2><?= $this->partial('posts/_link.phtml', array('post'=>$post)) ?></h2>

				<p><small>
					Category: <?= $post->getCategoryId() ?>, 
					by <?= $this->partial('users/_link.phtml', array('user'=>$post->user())) ?>
					on <?= DateTime::createFromFormat('U', $post->getCreated() )->format('d/m/Y') ?>
				</small></p>


				<p><?= substr($post->getContent(),0,250 )?></p>

				<p class="text-right">
					<a class="btn btn-primary" href="<?= $this->url(array('id'=>$post->id ), 'view_post') ?>">Read more...</a>
				</p>
				
			</article>
		<?php endforeach ?>


	</div>

	<div class="col-md-4 sidebar">
		<h4>Categories</h4>
		<div class="list-group">
			
		</div>
		
		<h4>Last posts</h4>
		<div class="list-group">
			
		</div>
	</div>
	
</div>