<div class="row">

	<div class="col-md-8">

		<div class="page-header">
			<h1><?= $this->title ?></h1>
			<p>Welcome to my blog</p>
		</div>

		<?php foreach ($this->entries as $post): ?>
			<article>
				<h2><a href="<?= $this->url(array('controller'=>'posts', 'action'=>'show','id'=>$post->id )) ?>"><?= $post->name ?></a></h2>

				<p><small>
					Category: <?= $post->getCategoryId() ?>, 
					by <?= $post->getUserId() ?>
					on <?= $post->getCreated() ?>
				</small></p>


				<p><?= substr($post->getContent(),0,250 )?></p>

				<p class="text-right">
					<a class="btn btn-primary" href="<?= $this->url(array('controller'=>'posts', 'action'=>'show','id'=>$post->id )) ?>">Read more...</a>
				</p>
				
			</article>
		<?php endforeach ?>


	</div>

	<div class="col-md-4 sidebar">
		<h4>Categories</h4>
		<div class="list-group">
			
		</div>
		
		<h4>Last posts</h4>
		<div class="list-group">
			
		</div>
	</div>
	
</div>