<div class="row">

	<div class="col-md-8">

		<div class="page-header">
			<h1><?= $this->partial('posts/_link.phtml', array('post'=>$this->post)) ?></h1>
			<?= $this->partial('posts/_header.phtml', array('post'=>$this->post)) ?>
		</div>


		<p><?= $this->post->getContent() ?></p>
			

		<hr/>

		<section class="comments">

            <h3>Comment this post</h3>

            <?php
                $this->form->setAction($this->url());
                echo $this->form;
            ?>


            <?= $this->partial('comments/_list.phtml', array('comments'=>$this->post->comments() )) ?>

            
        </section>


	</div>

	<?= $this->partial('posts/_news.phtml', array('categories'=>$this->categories, 'last_posts'=>$this->last_posts )) ?>
	
</div>