<div class="row">

	<div class="col-md-8">

		<div class="page-header">
			<h1><?= $this->partial('posts/_link.phtml', array('post'=>$this->post)) ?></h1>
			<?= $this->partial('posts/_header.phtml', array('post'=>$this->post)) ?>
		</div>


		<p><?= $this->post->getContent() ?></p>
			

		<hr/>

		<section class="comments">

            <h3>Comment this post</h3>

            <?php
                $this->form->setAction($this->url());
                echo $this->form;
            ?>


            <h3>2 Commentaires</h3>

            <div class="row">
                <div class="col-md-2">
                    <img width="100%" src="http://lorempicsum.com/futurama/100/100/4">
                </div>
                <div class="col-md-10">
                    <p><strong>Username</strong> 10 hours ago</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, laudantium voluptatibus quae doloribus dolorem earum dicta quasi. Fugit, eligendi, voluptatibus corporis deleniti perferendis accusantium totam harum dolor ab veniam laudantium!</p>
                </div>
            </div>
            <div class="row">
                <hr>
                <div class="col-md-2">
                    <img width="100%" src="http://lorempicsum.com/futurama/100/100/5">
                </div>
                <div class="col-md-10">
                    <p><strong>Username</strong> 11 days ago</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, laudantium voluptatibus quae doloribus dolorem earum dicta quasi. Fugit, eligendi, voluptatibus corporis deleniti perferendis accusantium totam harum dolor ab veniam laudantium!</p>
                </div>
            </div>
        </section>


	</div>

	<?= $this->partial('posts/_news.phtml', array('categories'=>$this->categories, 'last_posts'=>$this->last_posts )) ?>
	
</div>