acme_blog_homepage:
    pattern:  /
    defaults: { _controller: AcmeBlogBundle:Public:index }

acme_blog_category:
    pattern:  /category/{slug}
    defaults: { _controller: AcmeBlogBundle:Public:category }

acme_blog_author:
    pattern:  /author/{id}
    defaults: { _controller: AcmeBlogBundle:Public:author }

acme_blog_post_show:
    pattern:  /{slug}
    defaults: { _controller: "AcmeBlogBundle:Public:show" }