parameters:
#    acme_blog.example.class: Acme\BlogBundle\Example

services:
    twig.extension.timeago:
        class: Acme\BlogBundle\Twig\Extension\TimeAgoExtension
        arguments: [@translator]
        tags:
            - { name: twig.extension }

    twig.extension.gravatar:
        class: Acme\BlogBundle\Twig\Extension\GravatarExtension
        tags:
            - { name: twig.extension }