<?php

namespace Blog\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getActivePost(array $criteria = array())
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb = $qb
            ->select('p')
            ->from($this->getClassName(), 'p')
            ->where('p.created < :now')
            ->setParameter('now', new \DateTime())
            ->orderBy('p.created', 'DESC')
        ;

        if (isset($criteria['category'])) {
            $qb = $qb
                ->leftJoin('p.category', 'c')
                ->andWhere('c.slug = :category')
                ->setParameter('category', $criteria['category'])
            ;
        }

        if (isset($criteria['user'])) {
            $qb = $qb
                ->leftJoin('p.user', 'u')
                ->andWhere('u.id = :user')
                ->setParameter('user', $criteria['user'])
            ;
        }

        return $qb->getQuery();
    }

    public function getLastPost($limit = 2)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb = $qb
            ->select('p')
            ->from($this->getClassName(), 'p')
            ->where('p.created < :now')
            ->setParameter('now', new \DateTime())
            ->orderBy('p.created', 'DESC')
        ;

        return $qb
            ->getQuery()
            ->setMaxResults($limit)
            ->getResult()
        ;
    }
}
