<!-- display comments -->
<h3><?= sizeof($this->comments) ?> Comment(s)</h3>

<?php if($this->comments): ?>

	<?php foreach ($this->comments as $comment): ?>
		<div class="row">
			<div class="col-md-2">
				<img width="100%" src="http://lorempicsum.com/futurama/100/100/4">
			</div>
			<div class="col-md-10">
				<p><strong><?= $comment->username ?></strong> <?= $comment->days() ?> day(s) ago</p>
				<p><?= $comment->content ?></p>
			</div>
		</div>
	<?php endforeach ?>

<?php endif ?>