<h1>Edit post</h1>

<p><a href="<?php echo $this->url('admin/posts') ?>">< Back to posts</a></p>

<?php $this->form->prepare() ?>
<?php echo $this->form()->openTag($this->form); ?>
<?php $postForm = $this->form->get('post'); ?>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <?php echo $this->formLabel($postForm->get('name')) ?>
                <?php echo $this->formInput($postForm->get('name')) ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <?php echo $this->formLabel($postForm->get('category')) ?>
                <?php echo $this->formSelect($postForm->get('category')) ?>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <?php echo $this->formLabel($postForm->get('user')) ?>
                <?php echo $this->formSelect($postForm->get('user')) ?>
            </div>
        </div>
    </div>
    <div class="form-group required">
        <?php echo $this->formLabel($postForm->get('content')) ?>
        <?php echo $this->formTextarea($postForm->get('content')) ?>
    </div>
    <div class="submit">
        <?php echo $this->formSubmit($this->form->get('submit')) ?>
    </div>
<?php echo $this->formHidden($this->form->get('csrf_post')) ?>
<?php echo $this->form()->closeTag() ?>