<?php $this->headTitle('Blog') ?>

<div class="page-header">
    <h1>Blog</h1>
    <p class="lead">Welcome on my blog</p>
</div>

<?php foreach ($posts as $post) : ?>
<article>
    <h2><a href="<?php echo $this->url('posts/show', array('slug' => $post->getSlug())) ?>" title="<?php echo $post->getName() ?>"><?php echo $post->getName() ?></a></h2>
    <p>
        <small>
            Category : <a href="#"><?php echo $post->getCategory()->getName() ?></a>,
            by <a href="#"><?php echo $post->getUser()->getUsername() ?></a> on <em><?php echo $post->getCreated()->format('F jS, H:i') ?></em>
        </small>
    </p>
    <p><?php echo $this->truncate($post->getContent(), 450); ?></p>
    <p class="text-right">
        <a href="<?php echo $this->url('posts/show', array('slug' => $post->getSlug())) ?>" class="btn btn-primary">Read more...</a>
    </p>
</article>
<hr>
<?php endforeach; ?>

<?php
    echo $this->paginationControl(
        $paginator,
        null,
        'blog/common/_paginator',
        array('route' => 'posts/list')
    );
?>