<?php $this->headTitle($post->getName()) ?>

<div class="page-header">
    <h1><?php echo $post->getName() ?></h1>
    <p>
        <small>
            Category : <a href="<?php echo $this->url('posts/list', array('category' => $post->getCategory()->getSlug())) ?>"><?php echo $post->getCategory()->getName() ?></a>,
            by <a href="<?php echo $this->url('posts/list', array('author' => $post->getUser()->getId())) ?>"><?php echo $post->getUser()->getUsername() ?></a> on <em><?php echo $post->getCreated()->format('F jS, H:i') ?></em>
        </small>
    </p>
</div>

<article>
    <?php echo $this->markdown($post->getContent()); ?>
</article>

<hr>

<section class="comments">

    <h3>Comment this post</h3>

    <?php $form->prepare() ?>
    <?php echo $this->form()->openTag($form); ?>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <?php echo $this->formInput($form->get('mail')) ?>
                    <?php echo $this->formElementErrors($form->get('mail')) ?>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <?php echo $this->formInput($form->get('username')) ?>
                    <?php echo $this->formElementErrors($form->get('username')) ?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formTextarea($form->get('content')) ?>
            <?php echo $this->formElementErrors($form->get('content')) ?>
        </div>
        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit')) ?>
        </div>

    <?php echo $this->formHidden($form->get('csrf')) ?>
    <?php echo $this->form()->closeTag() ?>

    <h3><?php echo count($post->getComments()) . ' ' . $this->translatePlural('Comment', 'Comments', count($post->getComments())) ?></h3>

    <?php foreach ($post->getComments() as $comment) : ?>
    <div class="row">
        <div class="col-md-2">
            <img src="<?php echo $this->gravatar($comment->getMail()) ?>" width="100%">
        </div>
        <div class="col-md-10">
            <p><strong><?php echo $comment->getUsername() ?></strong> <?php echo $this->timeAgo($comment->getCreated()) ?></p>
            <p><?php echo nl2br($comment->getContent()) ?></p>
        </div>
    </div>
    <hr>
    <?php endforeach; ?>
</section>