<div class="page-header">
    <h1><?php echo $post->getName() ?></h1>
    <p>
        <small>
            Category : <a href="<?php echo $this->url('posts/list', array('category' => $post->getCategory()->getSlug())) ?>"><?php echo $post->getCategory()->getName() ?></a>,
            by <a href="<?php echo $this->url('posts/list', array('user' => $post->getUser()->getId())) ?>"><?php echo $post->getUser()->getUsername() ?></a> on <em><?php echo $post->getCreated()->format('F jS, H:i') ?></em>
        </small>
    </p>
</div>

<article>
    <?php echo $this->markdown($post->getContent()); ?>
</article>

<hr>

<section class="comments">

    <h3>Comment this post</h3>

    <div class="alert alert-danger"><strong>Oh snap !</strong> you did some errors</div>

    <form role="form">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Your email">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group has-error">
                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Your username">
                </div>
            </div>
        </div>
        <div class="form-group">
            <textarea class="form-control" rows="3" placeholder="Your comment"></textarea>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>

    <h3><?php echo count($post->getComments()) . ' ' . $this->translatePlural('Comment', 'Comments', count($post->getComments())) ?></h3>

    <?php foreach ($post->getComments() as $comment) : ?>
    <div class="row">
        <div class="col-md-2">
            <img src="<?php echo $this->gravatar($comment->getMail()) ?>" width="100%">
        </div>
        <div class="col-md-10">
            <p><strong><?php echo $comment->getUsername() ?></strong> <?php echo $this->timeAgo($comment->getCreated()) ?></p>
            <p><?php echo nl2br($comment->getContent()) ?></p>
        </div>
    </div>
    <hr>
    <?php endforeach; ?>
</section>