acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /


acme_blog_admin:
    resource: "@AcmeBlogBundle/Resources/config/routing_admin.yml"
    prefix:   /admin

acme_blog:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /