<h4>Categories</h4>
<div class="list-group">
    <?php if (count($categories)) : ?>
        <?php foreach ($categories as $category) : ?>
        <a href="<?php echo $this->url('posts/list', array('category' => $category->getSlug())) ?>" class="list-group-item">
            <span class="badge"><?php echo count($category->getPosts()) ?></span>
            <?php echo $category->getName() ?>
        </a>
        <?php endforeach; ?>
    <?php else : ?>
        <span class="list-group-item">
        <?php echo $this->translate('NO_CATEGORY_FOUND') ?>
        </span>
    <?php endif; ?>
</div>

<h4>Last posts</h4>
<div class="list-group">
    <?php if (count($posts)) : ?>
        <?php foreach ($posts as $post) : ?>
        <a href="<?php echo $this->url('posts/show', array('slug' => $post->getSlug())) ?>" class="list-group-item">
            <?php echo $post->getName() ?>
        </a>
        <?php endforeach; ?>
    <?php else : ?>
        <span class="list-group-item">
        <?php echo $this->translate('NO_POST_FOUND') ?>
        </span>
    <?php endif; ?>
</div>