<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>">Blog</a>
        </div>

        <div class="collapse navbar-collapse navbar-ex1-collapse navbar-right">
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url('home') ?>">< Back to front</a></li>
                <?php if ($this->identity()) : ?>
                <li><a href="<?php echo $this->url('admin/logout') ?>">Logout</a></li>
                <?php endif; ?>
            </ul>
        </div>

    </div><!-- /.container -->
</div>