<?php

namespace Acme\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function findAllWithCount(){
		return $this->getEntityManager()->getRepository('AcmeBlogBundle:Post')->createQueryBuilder('p')
			->select('p, c, COUNT(p) AS postCount')
			->join('p.category', 'c')
			->groupBy('c.id')
			->getQuery()
			->getResult()
		;
	}
}
