<?php

namespace Acme\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
	public function findAllQuery($conditions = array()){
		$qb = $this->createQueryBuilder('p')
			->select('p, c, u')
			->leftJoin('p.category', 'c')
			->leftJoin('p.user', 'u')
			->orderBy('p.created', 'DESC')
		;

		foreach($conditions as $k => $v)
			$qb->andWhere("$k = '$v'");

		$qb
			->getQuery()
		;
		return $qb;
	}
}
