<?php if ($this->errors) { ?>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <?php foreach ($this->errors as $message) { ?>
            <p><i class="glyphicon glyphicon-remove"> </i> <?php echo $message; ?></p>
        <?php } ?>
    </div>
<?php } ?>
<?php if ($this->infos) { ?>
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <?php foreach ($this->infos as $message) { ?>
            <p><i class="glyphicon glyphicon-info-sign"> </i> <?php echo $message; ?></p>
        <?php } ?>
    </div>
<?php } ?>
<?php if ($this->success) { ?>
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <?php foreach ($this->success as $message) { ?>
            <p><i class="glyphicon glyphicon-ok"> </i> <?php echo $message; ?></p>
        <?php } ?>
    </div>
<?php } ?>