<?php $this->headTitle('Admin') ?>

<?php $form->prepare() ?>
<?php echo $this->form()->openTag($form); ?>

    <h4 class="form-signin-heading">Please sign in</h4>
    <?php echo $this->formInput($form->get('username')) ?>
    <?php echo $this->formPassword($form->get('password')) ?>
    <?php echo $this->formSubmit($form->get('submit')) ?>

<?php echo $this->formHidden($form->get('csrf')) ?>
<?php echo $this->form()->closeTag() ?>