<div class="row">

	<div class="page-header">
		<h1>Users</h1>
	</div>

	<table class="table table-striped">
		<thead>
			<tr>
				<th>ID</th>
				<th>Username</th>
			</tr>
		</thead>
		<tbody>

		<?php foreach ($this->entries as $user): ?>
			<tr>
				<td><?= $user->id ?></td>
				<td><a href="<?= $this->url( array('id'=>$user->id), 'view_user') ?>"><?= $user->username ?></a></td>
			</tr>
		<?php endforeach ?>

			
		</tbody>
	</table>

</div>