<!DOCTYPE html>
<html>
<head>
	<title><?= $this->title ?></title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<meta charset="utf-8">
	<style type="text/css">
		body {
			padding-top: 50px;
		}
		.sidebar{
			margin-top: 50px;
		}
	</style>
</head>
<body>

	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<?= $this->url(array(), 'home') ?>">Blog</a>
			</div>

			<div class="collapse navbar-collapse navbar-ex1-collapse navbar-right">
				<ul class="nav navbar-nav">
					<li><a href="<?= $this->url(array(), 'admin') ?>">Admin</a></li>
				</ul>
			</div>

		</div>
	</nav>

	<div class="container">
		<?= $this->layout()->content; ?>
	</div>

</body>
</html>